name: Android Release Build

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  build_android_apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4' # Or flutter-version-file: pubspec.yaml

      - name: Display Flutter Version (for verification)
        run: flutter --version

      - name: Install Dependencies
        run: flutter pub get

      # --- ADD THESE STEPS FOR SIGNING ---
      - name: Decode Keystore File
        run: echo "${{ secrets.ANDROID_UPLOAD_KEYSTORE }}" | base64 --decode > android/app/release-key.jks
        # Ensure 'android/app/' is the correct path for your keystore

      - name: Create Keystore Properties File
        run: |
          echo "storeFile=release-key.jks" > android/key.properties
          echo "storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" >> android/key.properties
          echo "keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}" >> android/key.properties
        # Ensure 'android/' is the correct path for your key.properties

      - name: Build Android APK (Release)
        run: flutter build apk --release --split-per-abi

      - name: Upload Android APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/apk/release/
